import type { PropsLocale } from '@deepseek-ai/dsh-client-ui-slots';
import type { Context } from './context-types.ts';
import { type BrowserCardState } from './form.ts';
import type { PromptTextFieldId } from './prompts-form.ts';
import { type PromptsStatusState } from './prompts-status-client.ts';
import { SETTINGS_NAMESPACE } from './settings-namespace.ts';
import { type AutomationAssetsState } from './automation-assets-client.ts';
import type { AutomationAsset, AutomationAssetStatus } from '../automation-assets.ts';
export declare const name = "dsh-browser-client";
export declare const inject: string[];
export declare const NS = "dsh-browser.card";
export { SETTINGS_NAMESPACE };
export type BrowserSettingsCardProps = PropsLocale<typeof NS> & {
    /** Which view the Plugins page is asking for: the one-liner or the form body. */
    view: 'summary' | 'page';
    useBrowserSettings: <R>(selector: (snapshot: BrowserCardState) => R) => R;
    edit: (field: string, text: string) => void;
    resetField: (field: string) => void;
    save: () => void;
    discard: () => void;
    editPromptText: (id: PromptTextFieldId, text: string) => void;
    setPromptSkillEnabled: (enabled: boolean) => void;
    editPromptExtras: (text: string) => void;
    resetPromptExtras: () => void;
    usePromptsStatus: <R>(selector: (snapshot: PromptsStatusState) => R) => R;
    refreshPromptsStatus: () => void;
    useAutomationAssets: <R>(selector: (snapshot: AutomationAssetsState) => R) => R;
    refreshAutomationAssets: () => void;
    selectAutomationAsset: (id?: string) => void;
    saveAutomationAsset: (asset: Partial<AutomationAsset> & Pick<AutomationAsset, 'kind' | 'name'>) => Promise<void>;
    summarizeAutomationCandidate: (id: string) => Promise<void>;
    dismissAutomationCandidate: (id: string) => Promise<void>;
    validateAutomationAsset: (id: string) => Promise<void>;
    testAutomationAsset: (id: string, url: string, inputs: Record<string, string>, expectedRevision?: number) => Promise<void>;
    setAutomationAssetStatus: (id: string, status: AutomationAssetStatus, expectedRevision?: number) => Promise<void>;
    editAutomationAsset: (text: string) => void;
    setAssetTestUrl: (value: string) => void;
    setAssetTestInputs: (value: string) => void;
    requestSelectAutomationAsset: (id?: string) => void;
    requestNewAutomationAsset: (kind: AutomationAsset['kind']) => void;
    requestRefreshAutomationAssets: () => void;
    requestForkAutomationAsset: (id: string) => void;
    confirmLeaveAutomationAsset: () => void;
    cancelLeaveAutomationAsset: () => void;
    saveEditedAutomationAsset: () => Promise<unknown>;
    saveAndTestAutomationAsset: () => Promise<void>;
    activateAutomationAsset: () => Promise<void>;
};
export declare function apply(ctx: Context): void;
