export declare const styles: {
    readonly card: "dsb-card";
    readonly open: "dsb-open";
    readonly header: "dsb-header";
    readonly head: "dsb-head";
    readonly titleRow: "dsb-title-row";
    readonly name: "dsb-name";
    readonly description: "dsb-description";
    readonly badge: "dsb-badge";
    readonly chevron: "dsb-chevron";
    readonly chevronOpen: "dsb-chevron-open";
    readonly body: "dsb-body";
    readonly notice: "dsb-notice";
    readonly section: "dsb-section";
    readonly sectionHead: "dsb-section-head";
    readonly grid: "dsb-grid";
    readonly field: "dsb-field";
    readonly invalid: "dsb-invalid";
    readonly fieldHead: "dsb-field-head";
    readonly label: "dsb-label";
    readonly hint: "dsb-hint";
    readonly input: "dsb-input";
    readonly textarea: "dsb-textarea";
    readonly code: "dsb-code";
    readonly reset: "dsb-reset";
    readonly toggle: "dsb-toggle";
    readonly toggleLabel: "dsb-toggle-label";
    readonly check: "dsb-check";
    readonly advanced: "dsb-advanced";
    readonly footer: "dsb-footer";
    readonly status: "dsb-status";
    readonly failed: "dsb-failed";
    readonly actions: "dsb-actions";
    readonly primary: "dsb-primary";
    readonly secondary: "dsb-secondary";
};
export declare function ensureStyles(): void;
